version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: chatapp-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - chatapp-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      timeout: 30s
      retries: 3

volumes:
  rabbitmq_data:

networks:
  chatapp-network:
    driver: bridge